language: generic
sudo: required
dist: trusty

matrix:
  include:
    - env: LTS=default GHCVER=7.10.3
      addons:
        apt:
          sources: 
            - hvr-ghc
          packages:
            - ghc-7.10.3
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libleveldb-dev 
            - libzmq3-dev 
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev
    - env: LTS=3.22 GHCVER=7.10.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.2
            - alex-3.1.3
            - happy-1.19.4
            - libgmp-dev
            - libleveldb-dev 
            - libzmq3-dev 
            - libsnappy-dev 
            - pkg-config 
            - zlib1g-dev

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
  - if [[ "$LTS" == "default" ]]; then
      export STACK=stack;
    else
      export STACK="stack --stack-yaml stack-$LTS.yaml";
    fi 
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis/travis_long $STACK --no-terminal setup
  - travis/travis_long $STACK --no-terminal install hscolour

script:
  - travis/travis_long $STACK --no-terminal build --test --haddock
