resolver: lts-11.7
flags: {}
packages:
- haskoin-core
- haskoin-node
- haskoin-wallet
extra-deps:
- daemons-0.2.1
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.5.2
- git: git@github.com:bitemyapp/esqueleto
  commit: 6a86ee32e5b869a877151f74064572225e1a0398
