flags: {}
packages:
- '.'
- location: '..'
  subdirs:
    - haskoin-core
    - secp256k1-haskell
  extra-dep: true
extra-deps:
- concurrent-extra-0.7.0.10
- murmur3-1.0.1
- pbkdf-1.1.1.1
- cereal-0.5.1.0
resolver: lts-4.1
